// Auto-stub so the Orca port typechecks. Replace with the real module when this subsystem is wired.

export const bufferPtyShutdownReplayData: any = null
export type bufferPtyShutdownReplayData = any
export const clampUtf8Tail: any = null
export type clampUtf8Tail = any
export const clearPreHandlerPtyState: any = null
export type clearPreHandlerPtyState = any
export const drainPreHandlerPtyData: any = null
export type drainPreHandlerPtyData = any
export const drainRolledBackPtyShutdownData: any = null
export type drainRolledBackPtyShutdownData = any
export const isPtyDataHandlerShutdownPending: any = null
export type isPtyDataHandlerShutdownPending = any
export const isPtyPushDeliveryBlackholed: any = null
export type isPtyPushDeliveryBlackholed = any
export const ptyDataHandlers: any = null
export type ptyDataHandlers = any
export const ptyDataSidecars: any = null
export type ptyDataSidecars = any
export const ptyExitHandlers: any = null
export type ptyExitHandlers = any
export const ptyReplayHandlers: any = null
export type ptyReplayHandlers = any
export const ptyShutdownLifecycleHandlers: any = null
export type ptyShutdownLifecycleHandlers = any
export const ptyTeardownHandlers: any = null
export type ptyTeardownHandlers = any
export const recordPtyDataReceived: any = null
export type recordPtyDataReceived = any
export const restorePtyDataHandlersAfterFailedShutdown: any = null
export type restorePtyDataHandlersAfterFailedShutdown = any
export const unregisterPtyDataHandlers: any = null
export type unregisterPtyDataHandlers = any
export const bufferPtyShutdownData: any = null
export type bufferPtyShutdownData = any
