// Auto-stub so the Orca port typechecks. Replace with the real module when this subsystem is wired.

export type AgentProviderSessionMetadata = any
export const AgentProviderSessionRouting: any = null
export type AgentProviderSessionRouting = any
export type AgentStatusLiveEntryBuild = any
export const AgentStatusPayload: any = null
export type AgentStatusPayload = any
export const AgentStatusRouting: any = null
export type AgentStatusRouting = any
export const DropAgentStatusByTabPrefixOptions: any = null
export type DropAgentStatusByTabPrefixOptions = any
export const DropAgentStatusByWorktreeOptions: any = null
export type DropAgentStatusByWorktreeOptions = any
export const DropAgentStatusOptions: any = null
export type DropAgentStatusOptions = any
export type ResumableTuiAgent = any
export const RetainedAgentEntry: any = null
export type RetainedAgentEntry = any
export type SleepingAgentLaunchConfig = any
export const boundRecentlyRetiredAgentStatusPaneKeys: any = null
export type boundRecentlyRetiredAgentStatusPaneKeys = any
export const getAgentResumeArgv: any = null
export type getAgentResumeArgv = any
export const getLaunchConfigForStatusMetadata: any = null
export type getLaunchConfigForStatusMetadata = any
export const getTabIdFromPaneKey: any = null
export type getTabIdFromPaneKey = any
export const isRecentlyClosedAgentStatusTab: any = null
export type isRecentlyClosedAgentStatusTab = any
export const isResumableTuiAgent: any = null
export type isResumableTuiAgent = any
export const launchConfigRegistryEntriesEqual: any = null
export type launchConfigRegistryEntriesEqual = any
export const movePaneKeyedRecord: any = null
export type movePaneKeyedRecord = any
export const normalizeLaunchConfigRegistrationMetadata: any = null
export type normalizeLaunchConfigRegistrationMetadata = any
export const paneKeyMatchesAnyTabPrefix: any = null
export type paneKeyMatchesAnyTabPrefix = any
export const retainedAgentEntryFromLive: any = null
export type retainedAgentEntryFromLive = any
export const retireAgentPaneAuthorityAliases: any = null
export type retireAgentPaneAuthorityAliases = any
export const shouldReplaceRetainedWithLive: any = null
export type shouldReplaceRetainedWithLive = any
export const agentStatusTabAlreadyHasProtectedOrGeneratedTitle: any = null
export type agentStatusTabAlreadyHasProtectedOrGeneratedTitle = any
export const findAgentPaneWorktreeId: any = null
export type findAgentPaneWorktreeId = any
export const findCompletedOrphanPaneKeysForTabClose: any = null
export type findCompletedOrphanPaneKeysForTabClose = any
export const findTabForAgentEntry: any = null
export type findTabForAgentEntry = any
export const getLeafIdFromPaneKey: any = null
export type getLeafIdFromPaneKey = any
export const normalizePaneKeySet: any = null
export type normalizePaneKeySet = any
