// Auto-stub so the Orca port typechecks. Replace with the real module when this subsystem is wired.

export const BrowserBackResult: any = null
export type BrowserBackResult = any
export const BrowserCaptureStartResult: any = null
export type BrowserCaptureStartResult = any
export const BrowserCaptureStopResult: any = null
export type BrowserCaptureStopResult = any
export const BrowserCheckResult: any = null
export type BrowserCheckResult = any
export const BrowserClearResult: any = null
export type BrowserClearResult = any
export const BrowserClickResult: any = null
export type BrowserClickResult = any
export const BrowserConsoleEntry: any = null
export type BrowserConsoleEntry = any
export const BrowserConsoleResult: any = null
export type BrowserConsoleResult = any
export const BrowserCookie: any = null
export type BrowserCookie = any
export const BrowserCookieDeleteResult: any = null
export type BrowserCookieDeleteResult = any
export const BrowserCookieGetResult: any = null
export type BrowserCookieGetResult = any
export const BrowserCookieSetResult: any = null
export type BrowserCookieSetResult = any
export const BrowserDetectProfilesResult: any = null
export type BrowserDetectProfilesResult = any
export const BrowserDetectedInfo: any = null
export type BrowserDetectedInfo = any
export const BrowserDetectedProfileInfo: any = null
export type BrowserDetectedProfileInfo = any
export const BrowserDragResult: any = null
export type BrowserDragResult = any
export const BrowserErrorCode: any = null
export type BrowserErrorCode = any
export const BrowserEvalResult: any = null
export type BrowserEvalResult = any
export const BrowserFillResult: any = null
export type BrowserFillResult = any
export const BrowserFocusResult: any = null
export type BrowserFocusResult = any
export const BrowserGeolocationResult: any = null
export type BrowserGeolocationResult = any
export const BrowserGotoResult: any = null
export type BrowserGotoResult = any
export const BrowserHoverResult: any = null
export type BrowserHoverResult = any
export const BrowserInterceptDisableResult: any = null
export type BrowserInterceptDisableResult = any
export const BrowserInterceptEnableResult: any = null
export type BrowserInterceptEnableResult = any
export const BrowserInterceptedRequest: any = null
export type BrowserInterceptedRequest = any
export const BrowserKeypressResult: any = null
export type BrowserKeypressResult = any
export const BrowserNetworkEntry: any = null
export type BrowserNetworkEntry = any
export const BrowserNetworkLogResult: any = null
export type BrowserNetworkLogResult = any
export const BrowserPdfResult: any = null
export type BrowserPdfResult = any
export const BrowserProfileClearDefaultCookiesResult: any = null
export type BrowserProfileClearDefaultCookiesResult = any
export const BrowserProfileCreateResult: any = null
export type BrowserProfileCreateResult = any
export const BrowserProfileDeleteResult: any = null
export type BrowserProfileDeleteResult = any
export const BrowserProfileImportFromBrowserResult: any = null
export type BrowserProfileImportFromBrowserResult = any
export const BrowserProfileListResult: any = null
export type BrowserProfileListResult = any
export const BrowserReloadResult: any = null
export type BrowserReloadResult = any
export const BrowserScreencastDialogClosedResult: any = null
export type BrowserScreencastDialogClosedResult = any
export const BrowserScreencastDialogResult: any = null
export type BrowserScreencastDialogResult = any
export const BrowserScreencastEndResult: any = null
export type BrowserScreencastEndResult = any
export const BrowserScreencastErrorResult: any = null
export type BrowserScreencastErrorResult = any
export const BrowserScreencastReadyResult: any = null
export type BrowserScreencastReadyResult = any
export const BrowserScreencastResult: any = null
export type BrowserScreencastResult = any
export const BrowserScreenshotResult: any = null
export type BrowserScreenshotResult = any
export const BrowserScrollResult: any = null
export type BrowserScrollResult = any
export const BrowserSelectAllResult: any = null
export type BrowserSelectAllResult = any
export const BrowserSelectResult: any = null
export type BrowserSelectResult = any
export const BrowserSnapshotRef: any = null
export type BrowserSnapshotRef = any
export const BrowserSnapshotResult: any = null
export type BrowserSnapshotResult = any
export const BrowserTabCreateResult: any = null
export type BrowserTabCreateResult = any
export const BrowserTabCurrentResult: any = null
export type BrowserTabCurrentResult = any
export const BrowserTabInfo: any = null
export type BrowserTabInfo = any
export const BrowserTabListResult: any = null
export type BrowserTabListResult = any
export const BrowserTabProfileCloneResult: any = null
export type BrowserTabProfileCloneResult = any
export const BrowserTabProfileShowResult: any = null
export type BrowserTabProfileShowResult = any
export const BrowserTabSetProfileResult: any = null
export type BrowserTabSetProfileResult = any
export const BrowserTabShowResult: any = null
export type BrowserTabShowResult = any
export const BrowserTabSwitchResult: any = null
export type BrowserTabSwitchResult = any
export const BrowserTypeResult: any = null
export type BrowserTypeResult = any
export const BrowserUploadResult: any = null
export type BrowserUploadResult = any
export const BrowserViewportResult: any = null
export type BrowserViewportResult = any
export const BrowserWaitResult: any = null
export type BrowserWaitResult = any
