// Auto-stub so the Orca port typechecks. Replace with the real module when this subsystem is wired.

export const BROWSER_UNAVAILABLE_ERROR_CODE: any = null
export type BROWSER_UNAVAILABLE_ERROR_CODE = any
export const HEADLESS_RUNTIME_WINDOW_ID: any = null
export type HEADLESS_RUNTIME_WINDOW_ID = any
export const UNPUBLISHED_WORKTREE_PUBLICATION_EPOCH: any = null
export type UNPUBLISHED_WORKTREE_PUBLICATION_EPOCH = any
export const browserUnavailableMessage: any = null
export type browserUnavailableMessage = any
export const CliRuntimeState: any = null
export type CliRuntimeState = any
export const CliStatusResult: any = null
export type CliStatusResult = any
export const DeviceScope: any = null
export type DeviceScope = any
export const RuntimeBrowserDriverState: any = null
export type RuntimeBrowserDriverState = any
export const RuntimeDesktopWindowStatus: any = null
export type RuntimeDesktopWindowStatus = any
export const RuntimeGraphStatus: any = null
export type RuntimeGraphStatus = any
export const RuntimeMobileSessionAgentTab: any = null
export type RuntimeMobileSessionAgentTab = any
export const RuntimeMobileSessionBrowserTab: any = null
export type RuntimeMobileSessionBrowserTab = any
export const RuntimeMobileSessionClientTab: any = null
export type RuntimeMobileSessionClientTab = any
export const RuntimeMobileSessionCreateTerminalResult: any = null
export type RuntimeMobileSessionCreateTerminalResult = any
export const RuntimeMobileSessionFileTab: any = null
export type RuntimeMobileSessionFileTab = any
export const RuntimeMobileSessionMarkdownTab: any = null
export type RuntimeMobileSessionMarkdownTab = any
export const RuntimeMobileSessionRetiredTerminalSurface: any = null
export type RuntimeMobileSessionRetiredTerminalSurface = any
export const RuntimeMobileSessionSnapshotTab: any = null
export type RuntimeMobileSessionSnapshotTab = any
export const RuntimeMobileSessionTabCloseResult: any = null
export type RuntimeMobileSessionTabCloseResult = any
export const RuntimeMobileSessionTabGroup: any = null
export type RuntimeMobileSessionTabGroup = any
export const RuntimeMobileSessionTabMove: any = null
export type RuntimeMobileSessionTabMove = any
export const RuntimeMobileSessionTabMoveResult: any = null
export type RuntimeMobileSessionTabMoveResult = any
export const RuntimeMobileSessionTabsRemovedResult: any = null
export type RuntimeMobileSessionTabsRemovedResult = any
export const RuntimeMobileSessionTabsResult: any = null
export type RuntimeMobileSessionTabsResult = any
export const RuntimeMobileSessionTabsSnapshot: any = null
export type RuntimeMobileSessionTabsSnapshot = any
export const RuntimeMobileSessionTerminalClientTab: any = null
export type RuntimeMobileSessionTerminalClientTab = any
export const RuntimeMobileSessionTerminalTab: any = null
export type RuntimeMobileSessionTerminalTab = any
export const RuntimeMobileTerminalTheme: any = null
export type RuntimeMobileTerminalTheme = any
export const RuntimeNativeChatLaunchDraftResolution: any = null
export type RuntimeNativeChatLaunchDraftResolution = any
export const RuntimeRendererSyncWindowGraph: any = null
export type RuntimeRendererSyncWindowGraph = any
export const RuntimeSessionTabCloseReason: any = null
export type RuntimeSessionTabCloseReason = any
export const RuntimeStatus: any = null
export type RuntimeStatus = any
export const RuntimeSyncWindowGraph: any = null
export type RuntimeSyncWindowGraph = any
export const RuntimeSyncWindowGraphResult: any = null
export type RuntimeSyncWindowGraphResult = any
export const RuntimeSyncedLeaf: any = null
export type RuntimeSyncedLeaf = any
export const RuntimeSyncedTab: any = null
export type RuntimeSyncedTab = any
export const RuntimeTerminalDriverState: any = null
export type RuntimeTerminalDriverState = any
