// Auto-stub so the Orca port typechecks. Replace with the real module when this subsystem is wired.

export const RuntimeTerminalAgentStatus: any = null
export type RuntimeTerminalAgentStatus = any
export const RuntimeTerminalAgentStatusState: any = null
export type RuntimeTerminalAgentStatusState = any
export const RuntimeTerminalClose: any = null
export type RuntimeTerminalClose = any
export const RuntimeTerminalCreate: any = null
export type RuntimeTerminalCreate = any
export const RuntimeTerminalCreateRequestPayload: any = null
export type RuntimeTerminalCreateRequestPayload = any
export const RuntimeTerminalFocus: any = null
export type RuntimeTerminalFocus = any
export const RuntimeTerminalInteractiveWait: any = null
export type RuntimeTerminalInteractiveWait = any
export const RuntimeTerminalInteractiveWaitSource: any = null
export type RuntimeTerminalInteractiveWaitSource = any
export const RuntimeTerminalListHostScope: any = null
export type RuntimeTerminalListHostScope = any
export const RuntimeTerminalListResult: any = null
export type RuntimeTerminalListResult = any
export const RuntimeTerminalOrphanAdoptionClaim: any = null
export type RuntimeTerminalOrphanAdoptionClaim = any
export const RuntimeTerminalOrphanAdoptionRequest: any = null
export type RuntimeTerminalOrphanAdoptionRequest = any
export const RuntimeTerminalOrphanAdoptionResult: any = null
export type RuntimeTerminalOrphanAdoptionResult = any
export const RuntimeTerminalOrphanTopology: any = null
export type RuntimeTerminalOrphanTopology = any
export const RuntimeTerminalOrphanTopologyGroup: any = null
export type RuntimeTerminalOrphanTopologyGroup = any
export const RuntimeTerminalOrphanTopologyTab: any = null
export type RuntimeTerminalOrphanTopologyTab = any
export const RuntimeTerminalPresentation: any = null
export type RuntimeTerminalPresentation = any
export const RuntimeTerminalPromptDelivery: any = null
export type RuntimeTerminalPromptDelivery = any
export const RuntimeTerminalPromptStage: any = null
export type RuntimeTerminalPromptStage = any
export const RuntimeTerminalRead: any = null
export type RuntimeTerminalRead = any
export const RuntimeTerminalRename: any = null
export type RuntimeTerminalRename = any
export const RuntimeTerminalResolvePane: any = null
export type RuntimeTerminalResolvePane = any
export const RuntimeTerminalSend: any = null
export type RuntimeTerminalSend = any
export const RuntimeTerminalShow: any = null
export type RuntimeTerminalShow = any
export const RuntimeTerminalSplit: any = null
export type RuntimeTerminalSplit = any
export const RuntimeTerminalState: any = null
export type RuntimeTerminalState = any
export const RuntimeTerminalSummary: any = null
export type RuntimeTerminalSummary = any
export const RuntimeTerminalVisualGroupNode: any = null
export type RuntimeTerminalVisualGroupNode = any
export const RuntimeTerminalVisualLayout: any = null
export type RuntimeTerminalVisualLayout = any
export const RuntimeTerminalVisualLayoutNode: any = null
export type RuntimeTerminalVisualLayoutNode = any
export const RuntimeTerminalVisualPaneNode: any = null
export type RuntimeTerminalVisualPaneNode = any
export const RuntimeTerminalVisualTab: any = null
export type RuntimeTerminalVisualTab = any
export const RuntimeTerminalVisualTerminalNode: any = null
export type RuntimeTerminalVisualTerminalNode = any
export const RuntimeTerminalWait: any = null
export type RuntimeTerminalWait = any
export const RuntimeTerminalWaitBlockedReason: any = null
export type RuntimeTerminalWaitBlockedReason = any
export const RuntimeTerminalWaitCondition: any = null
export type RuntimeTerminalWaitCondition = any
export const RuntimeWorktreeTerminalCloseResult: any = null
export type RuntimeWorktreeTerminalCloseResult = any
export const RuntimeWorktreeTerminalSleepResult: any = null
export type RuntimeWorktreeTerminalSleepResult = any
