// Auto-stub so the Orca port typechecks. Replace with the real module when this subsystem is wired.

export const capPrRefreshStates: any = null
export type capPrRefreshStates = any
export const deletePRRefreshStartedEntry: any = null
export type deletePRRefreshStartedEntry = any
export const inflightProjectViewRequests: any = null
export type inflightProjectViewRequests = any
export const inflightWorkItemsRequests: any = null
export type inflightWorkItemsRequests = any
export const isFresh: any = null
export type isFresh = any
export const prChecksCacheSuffix: any = null
export type prChecksCacheSuffix = any
export const prRefreshStartedEntryKey: any = null
export type prRefreshStartedEntryKey = any
export const prRequestGenerations: any = null
export type prRequestGenerations = any
export const projectViewRequestKey: any = null
export type projectViewRequestKey = any
export const projectViewSourceScope: any = null
export type projectViewSourceScope = any
export const releaseProviderRequestSlot: any = null
export type releaseProviderRequestSlot = any
export const sortWorkItemsByNumber: any = null
export type sortWorkItemsByNumber = any
export const withBoundedCacheEntry: any = null
export type withBoundedCacheEntry = any
export const acquireProviderRequestSlot: any = null
export type acquireProviderRequestSlot = any
export const clearInflightWorkItemsForRepo: any = null
export type clearInflightWorkItemsForRepo = any
export const inflightChecksRequests: any = null
export type inflightChecksRequests = any
export const inflightCommentsRequests: any = null
export type inflightCommentsRequests = any
export const inflightIssueRequests: any = null
export type inflightIssueRequests = any
export const inflightPRRequests: any = null
export type inflightPRRequests = any
export const prRefreshStartedHostedReviewEntries: any = null
export type prRefreshStartedHostedReviewEntries = any
