// Auto-stub so the Orca port typechecks. Replace with the real module when this subsystem is wired.

export const getGitHubWorkItemRequestContext: any = null
export type getGitHubWorkItemRequestContext = any
export const getGitHubWorkItemSourceCacheScope: any = null
export type getGitHubWorkItemSourceCacheScope = any
export const getGitHubWorkItemSourceHostId: any = null
export type getGitHubWorkItemSourceHostId = any
export const getGitHubWorkItemSourceSettings: any = null
export type getGitHubWorkItemSourceSettings = any
export const getPRRefreshRuntimeRepoTarget: any = null
export type getPRRefreshRuntimeRepoTarget = any
export const getRuntimeRepoTarget: any = null
export type getRuntimeRepoTarget = any
export const getWorkItemsCacheKeyForOwner: any = null
export type getWorkItemsCacheKeyForOwner = any
export const inflightWorkItemsRequests: any = null
export type inflightWorkItemsRequests = any
export const isFresh: any = null
export type isFresh = any
export const isGitHubUnavailableWorkItemsError: any = null
export type isGitHubUnavailableWorkItemsError = any
export const listGitHubWorkItemsForRepo: any = null
export type listGitHubWorkItemsForRepo = any
export const prChecksCacheSuffix: any = null
export type prChecksCacheSuffix = any
export const releaseProviderRequestSlot: any = null
export type releaseProviderRequestSlot = any
export const sortWorkItemsByNumber: any = null
export type sortWorkItemsByNumber = any
export const withBoundedCacheEntry: any = null
export type withBoundedCacheEntry = any
export const countGitHubWorkItemsForRepo: any = null
export type countGitHubWorkItemsForRepo = any
export const getGitHubRepoSourceSettings: any = null
export type getGitHubRepoSourceSettings = any
export const settingsForGitHubRepoOwner: any = null
export type settingsForGitHubRepoOwner = any
