// Auto-stub so the Orca port typechecks. Replace with the real module when this subsystem is wired.

export const PET_SIZE_MAX: any = null
export type PET_SIZE_MAX = any
export const PET_SIZE_MIN: any = null
export type PET_SIZE_MIN = any
export const UISlice: any = null
export type UISlice = any
export const UISliceGet: any = null
export type UISliceGet = any
export const clampPetSize: any = null
export type clampPetSize = any
export const hydrateUnexpectedSignoutDismissal: any = null
export type hydrateUnexpectedSignoutDismissal = any
export const hydratedUIPartialMatchesState: any = null
export type hydratedUIPartialMatchesState = any
export const migrateStatusBarItems: any = null
export type migrateStatusBarItems = any
export const normalizeHydratedVisibleWorkspaceHostIds: any = null
export type normalizeHydratedVisibleWorkspaceHostIds = any
export const preserveStringArrayIdentity: any = null
export type preserveStringArrayIdentity = any
export const restoreAvailableDefaultTaskProvider: any = null
export type restoreAvailableDefaultTaskProvider = any
export const sanitizeHydratedActiveView: any = null
export type sanitizeHydratedActiveView = any
export const sanitizePersistedRepoIds: any = null
export type sanitizePersistedRepoIds = any
export const sanitizePersistedSidebarWidth: any = null
export type sanitizePersistedSidebarWidth = any
export const sanitizeShowDotfilesByWorktree: any = null
export type sanitizeShowDotfilesByWorktree = any
export const sanitizeWorkspaceCleanupDismissals: any = null
export type sanitizeWorkspaceCleanupDismissals = any
export const hydrateTrustedOrcaHooks: any = null
export type hydrateTrustedOrcaHooks = any
export const presetToQuery: any = null
export type presetToQuery = any
